### ISSUE TITLE
Parameter 'a' implicitly has an 'any' type. 

### ISSUE THREAD

**Issue by reigelj** [Alberthaff/ngx-papaparse#1]
ngx-papaparse- 1.2.2
node - v6.9.1
npm- 5.0.4
angular- 4.2.6
typescript- 2.3.4

`C:/USA/Intranet/Client/node_modules/ngx-papaparse/dist/lib/papaparse.interface.d.ts(45,28): error TS7006: Parameter 'b' implicitly has an 'any' type.`

**Comment by Alberthaff** [comment]
Thanks.
I have changed the interface to following:
`beforeFirstChunk?: (chunk:string) => string|void`

Which should be in accordance with the official [PapaParse documentation](http://papaparse.com/docs#config). :-)

The change is available in latest version.

**Comment by Alberthaff** [comment]
Thanks.
I have changed the interface to following:
`beforeFirstChunk?: (chunk:string) => string|void`

Which should be in accordance with the official [PapaParse documentation](http://papaparse.com/docs#config). :-)

The change is available in latest version.

**Comment by rrguez** [comment]
Hi, im using ngx-papaparse and found some problems, i dont know if are issues:
ngx-papaparse 1.2.4
Angular 4.
1.- when configuring a chunk function, dont work, only complete function works.
2.- using this.papa.setLocalChunkSize('10240') throws an error, y fiex that by change 
 PapaParseService.prototype.setLocalChunkSize = function (value) {
    this.papa.setLocalChunkSize(value)     //old way
    this.papa.localChunkSize=value; //new way
    };
on papaparse.service.js file.
but im still worried about first question

**Comment by Alberthaff** [comment]
Hi @rrguez.
Thanks for your comment.

Yes, you are correct. According to the Papa Parse docs, the correct way is:
`papa.LocalChunkSize = value;`

The function within the ngx-papaparse wrapper has been changed to accept a number instead of a string and will parse the value to the code above.

The changes is available in ngx-papaparse version 1.2.5.

Please note that the `LocalChunkSize`-parameter is only used when parsing a local or remote file, and not a string. If you need a periodic callback during parsing of a string, please see the `step`-callback.
