### ISSUE TITLE
Question - documentation parse big file using streaming feature in angular

### ISSUE THREAD

**Issue by Jerome2606** [alberthaff/ngx-papaparse#36]
I can find a good example on how to provide an upload form input and how to parse it using ngx-papaparse with the streaming feature (320 MB file size)

Can you help me with a simple example how to achieve this plz ?

**Comment by alberthaff** [comment]
When parsing big files, it is recommended to use a worker-thread. This will keep the site responsive, since Papa Parse will run in a separate thread.

You have to set the `worker`-option to `true` and configure the global options for ngx-papaparse, to support workers.

Please take a look at [using serviceworkers](https://alberthaff.dk/projects/ngx-papaparse/docs/v3/parsing-csv/using-serviceworkers). It should point you in the right direction. :-)

**Comment by Jerome2606** [comment]
I'm trying to add the asset section in my angular.json but it's not accepted.
Can you guide me with the syntax that I need to use with the new angular.json and not the angular.cli.json ?

**Comment by alberthaff** [comment]
You have to add it to assets in `angular.json`:

```json
{
  "projects": {
    "my-project": {
        "build": {
          "options": {
            "assets": [
              {
                "glob": "**/papaparse.min.js",
                "input": "node_modules/papaparse",
                "output": "/lib"
              }
            ]
          }
        }
      }
    }
  }
}
```

**Comment by Jerome2606** [comment]
Thanks @alberthaff I don't why the intellisense of VS code was putting the lines in red.
Nevermind, it's working as expected.

millions of log files parsed so quickly :)

Thanks

**Comment by alberthaff** [comment]
@Jerome2606 You're welcome. :-)
